# Generated by Django 4.1 on 2022-08-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_suepradmin',
            new_name='is_superadmin',
        ),
    ]
