# Generated by Django 4.1 on 2022-08-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='dexcription',
            new_name='description',
        ),
    ]
